SELECT 
UGB.TITLE, 
UGB.BOARD_ID, 
UGR.REPLY_ID, 
UGR.WRITER_ID, 
UGR.CONTENTS, 
DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d')
FROM
USED_GOODS_BOARD UGB
JOIN USED_GOODS_REPLY UGR
on UGB.BOARD_ID = UGR.BOARD_ID
where UGB.CREATED_DATE between '2022-10-01' and '2022-10-31'
order by UGR.CREATED_DATE ASC, UGB.TITLE asc
# 게시글 제목 : TITLE
# 게시글 ID : BOARD_ID
# 댓글 ID : REPLY_ID 
# 댓글 작성자 ID : WRITER_ID
# 댓글 내용 : CONTENTS
# 댓글 작성일 : CREATED_DATE	
# SELECT * FROM USED_GOODS_REPLY